# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'obligatorio-final' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for obligatorio-final
  pod 'Kingfisher', '~> 7.7’
  pod 'IQKeyboardManager', '~> 6.5'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
end
